apiVersion: v1
kind: PersistentVolume
metadata:
  name: pod-startup-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/log/podstartup  # will appear on your host machine
  persistentVolumeReclaimPolicy: Retain