apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pod-time-measure-controller-startup-pvc
  namespace: pod-time-measure-controller-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi