---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - monitoring.karthik.dev
  resources:
  - podstartups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.karthik.dev
  resources:
  - podstartups/finalizers
  verbs:
  - update
- apiGroups:
  - monitoring.karthik.dev
  resources:
  - podstartups/status
  verbs:
  - get
  - patch
  - update
